// Package project derives a ticket's control state — the human's relationship to
// it — from the append-only log, and renders the generated state.md projection.
package project

import (
	"fmt"
	"os"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"draiver/internal/event"
	"draiver/internal/store"
	"draiver/internal/ticketlog"
)

// State is a control state: the human's relationship to the ticket, not its
// progress.
type State string

const (
	Running State = "Running"  // agent working, no action; rendered as a count
	NeedsMe State = "Needs me" // unresolved escalation — the board
	Review  State = "Review"   // agent claims done; a claim, not a fact
	Done    State = "Done"     // closed
)

// Meta is the identity carried in spec.md frontmatter.
type Meta struct {
	ID       string `yaml:"id"`
	Title    string `yaml:"title"`
	Project  string `yaml:"project"`
	Team     string `yaml:"team"`
	Assignee string `yaml:"assignee"`
}

// Ticket is a ticket's identity plus its derived control state and log.
type Ticket struct {
	Meta
	State           State
	Events          []event.Event
	OpenEscalations []event.Event // escalations with no later resolution
}

// lifecycleTypes are the events that move a ticket between control states.
func isLifecycle(t string) bool {
	switch t {
	case "escalation", "review", "done":
		return true
	}
	return false
}

// Derive computes the control state and the set of unresolved escalations from a
// ticket's events (which must be in seq order). Precedence, first match wins:
// Done > Needs me (open escalation) > Review > Running.
func Derive(events []event.Event) (State, []event.Event) {
	resolved := map[int]bool{}
	for _, e := range events {
		if e.Type == "resolution" {
			for _, r := range e.Refs {
				resolved[r] = true
			}
		}
	}

	var open []event.Event
	var lastLifecycle *event.Event
	for i := range events {
		e := events[i]
		if e.Type == "escalation" && !resolved[e.Seq] {
			open = append(open, e)
		}
		if isLifecycle(e.Type) {
			lastLifecycle = &events[i]
		}
	}

	switch {
	case lastLifecycle != nil && lastLifecycle.Type == "done":
		return Done, open
	case len(open) > 0:
		return NeedsMe, open
	case lastLifecycle != nil && lastLifecycle.Type == "review":
		return Review, open
	default:
		return Running, open
	}
}

// Load reads a ticket's spec metadata and log and derives its state.
func Load(root store.Root, id string) (Ticket, error) {
	events, err := ticketlog.Read(root, id)
	if err != nil {
		return Ticket{}, err
	}
	meta, err := loadMeta(root.SpecPath(id))
	if err != nil {
		return Ticket{}, err
	}
	if meta.ID == "" {
		meta.ID = id
	}
	if meta.Title == "" {
		meta.Title = id
	}
	state, open := Derive(events)
	return Ticket{Meta: meta, State: state, Events: events, OpenEscalations: open}, nil
}

// LoadAll loads every ticket under the root, sorted by id.
func LoadAll(root store.Root) ([]Ticket, error) {
	ids, err := root.ListTickets()
	if err != nil {
		return nil, err
	}
	tickets := make([]Ticket, 0, len(ids))
	for _, id := range ids {
		t, err := Load(root, id)
		if err != nil {
			return nil, err
		}
		tickets = append(tickets, t)
	}
	return tickets, nil
}

func loadMeta(specPath string) (Meta, error) {
	data, err := os.ReadFile(specPath)
	if err != nil {
		if os.IsNotExist(err) {
			return Meta{}, nil
		}
		return Meta{}, fmt.Errorf("read spec: %w", err)
	}
	s := string(data)
	if !strings.HasPrefix(s, "---\n") {
		return Meta{}, nil // no frontmatter
	}
	rest := s[len("---\n"):]
	end := strings.Index(rest, "\n---")
	if end < 0 {
		return Meta{}, nil
	}
	var m Meta
	if err := yaml.Unmarshal([]byte(rest[:end]), &m); err != nil {
		return Meta{}, fmt.Errorf("parse spec frontmatter: %w", err)
	}
	return m, nil
}

// RenderState renders the generated state.md projection. It is a projection of
// the log and must never be read back as truth.
func RenderState(t Ticket, now time.Time) []byte {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "ticket: %s\n", t.ID)
	fmt.Fprintf(&b, "state: %s\n", t.State)
	fmt.Fprintf(&b, "open_escalations: %d\n", len(t.OpenEscalations))
	fmt.Fprintf(&b, "events: %d\n", len(t.Events))
	fmt.Fprintf(&b, "generated: %s\n", now.UTC().Format(time.RFC3339))
	b.WriteString("---\n\n")
	b.WriteString("<!-- GENERATED by `draiver status` — do not edit. Projection of the log. -->\n\n")
	fmt.Fprintf(&b, "# %s — %s\n\n", t.ID, t.Title)
	fmt.Fprintf(&b, "**State:** %s\n\n", t.State)
	if len(t.OpenEscalations) > 0 {
		b.WriteString("## Open escalations\n\n")
		for _, e := range t.OpenEscalations {
			fmt.Fprintf(&b, "- #%d: %s\n", e.Seq, firstLine(e.Body))
		}
		b.WriteString("\n")
	}
	if len(t.Events) > 0 {
		last := t.Events[len(t.Events)-1]
		fmt.Fprintf(&b, "**Last activity:** #%d %s by %s at %s\n",
			last.Seq, last.Type, last.Actor, last.TS.UTC().Format(time.RFC3339))
	}
	return []byte(b.String())
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
